### ISSUE TITLE
Wrong instruction to execute the web app

### ISSUE THREAD

**Issue by rafanog** [auth0-community/auth0-symfony-php-web-app#27]
The command to execute the sample app for Symfony regular web app asks for the pcntl extension to be installed if the server:start command is going to be used:

![image](https://user-images.githubusercontent.com/15782359/37725296-0cc01a76-2d09-11e8-881c-0ee1439237b0.png)

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
