### ISSUE TITLE
Missing state parameter

### ISSUE THREAD

**Issue by rafanog** [auth0-community/auth0-symfony-php-web-app#28]
The state parameter is missing on the callback url when the user enters the credentials:
![image](https://user-images.githubusercontent.com/15782359/37726521-f8b94c2a-2d0b-11e8-9380-232155f3f3f8.png)
When the user selects the account that was used last time to login instead of entering the credentials, the state parameter is returned in the callback:
![image](https://user-images.githubusercontent.com/15782359/37726445-c46c7f50-2d0b-11e8-9154-ed9a91ea0160.png)

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
