### ISSUE TITLE
Is this sample web app compatible with SF4?

### ISSUE THREAD

**Issue by shahroznawaz** [auth0-community/auth0-symfony-php-web-app#36]
Hi there, I'm looking to integrate Auth0 with SF4. Is this app compatible? what changes I need to made can anybody guide?

**Comment by zhil** [comment]
I tried symfony guide and its still not working.
neither php guide. :(

@shahroznawaz just wonder - did you fixed this issues? Is Auth0 working for you now?

**Comment by JimCMorrison** [comment]
After reviewing as a team we’ve decided to deprecate this repository 
in favor of focusing on more actively leveraged projects. We will be 
closing all open issues and pull requests, as a result of these changes.  
If you need any further help from our team you can reach out at 
[Community.Auth0.com](https://community.auth0.com/) -- Thank you for your contributions.
